name: Update README

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update README with recent activity

    steps:
      - uses: actions/checkout@v3
      - uses: udaypali/github-activity-readme@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          GH_USERNAME: udaypali
